#!/usr/bin/env bash
#Script to install nginx on server
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
rm /var/www/html/*
echo Hello World! > /var/www/html/index.html
sudo service nginx restart
