#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.
invisible() {
	echo "I am invincible!!!"
}
trap invisible SIGTERM
while true
do
        echo "To infinity and beyond"
        sleep 2
done
